// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFUgWXAZklnOCzqVobAkOb9xOPRknzjkE',
    appId: '1:264952142675:web:947a5f54a8327195c19fa6',
    messagingSenderId: '264952142675',
    projectId: 'reelsgellery',
    authDomain: 'reelsgellery.firebaseapp.com',
    storageBucket: 'reelsgellery.firebasestorage.app',
    measurementId: 'G-4WZ9TV24T6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDW5idmx37Kfn5dfh2wGfpztawATIB7laI',
    appId: '1:264952142675:android:d7b7352bbe63584ec19fa6',
    messagingSenderId: '264952142675',
    projectId: 'reelsgellery',
    storageBucket: 'reelsgellery.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGWWPvdEqmcNzkl64Ctv776a-J_0jMAdQ',
    appId: '1:264952142675:ios:fa9619b8ab39dfb1c19fa6',
    messagingSenderId: '264952142675',
    projectId: 'reelsgellery',
    storageBucket: 'reelsgellery.firebasestorage.app',
    iosBundleId: 'com.example.reelgallry',
  );
}
