import 'package:hive/hive.dart';

part 'video_data.g.dart'; // This file will be generated by build_runner

// Defines the data structure for video metadata to be stored in Hive.
@HiveType(typeId: 0)
class VideoData extends HiveObject {

  @HiveField(0)
  bool isLiked;

  // Field to store the total number of likes.
  @HiveField(1)
  int likeCount;

  // Field to store a list of comments on the video.
  @HiveField(2)
  List<String> comments;

  // Constructor for the VideoData class.
  VideoData({
    this.isLiked = false,
    this.likeCount = 0,
    required this.comments,
  });
}