import 'package:hive/hive.dart';

part 'video_data.g.dart'; // This file will be generated by build_runner

@HiveType(typeId: 0)
class VideoData extends HiveObject {
  @HiveField(0)
  bool isLiked;

  @HiveField(1)
  int likeCount;

  @HiveField(2)
  List<String> comments;

  VideoData({
    this.isLiked = false,
    this.likeCount = 0,
    required this.comments,
  });
}